### ISSUE TITLE
Theater mode black background doesn't get fully hidden by css rule anymore

### ISSUE THREAD

**Issue by SW1FT** [ParticleCore/Particle#197]
![ytbug](https://cloud.githubusercontent.com/assets/6627739/12285046/f5ef58c8-b9ad-11e5-9ae2-9bc35fc55c6e.png)

I don't know if this has anything to do with YT+ but fully hiding the black background of the theater mode doesn't work anymore with this css rule: 
`.watch-stage-mode #theater-background {
     display: none;
   }`

EDIT: I should also add that the background is fully hidden when the player is not minimized.

**Comment by ParticleCore** [comment]
This has never been a YT+ feature and I am also unable to reproduce it with just the following rule:

````css
#theater-background {display: none}
````

It is possible that another extension/stylish rule is conflicting with that. Inspecting the black element will help understand exactly what is happening in there, if it is just the `#player-api` getting enlarged to the left or if it is part of the `#theater-background` that is showing on the left when it shouldn't.

**Comment by SW1FT** [comment]
You were right, it's just the #player-api that's enlarged to the left. I have no clue regarding what's causing this as I've disabled all addons but YT+ and stylish (only using that one stylish rule).

**Comment by ParticleCore** [comment]
Strange, can you share your YT+ settings so that I can see if it has anything to do with it somehow?

**Comment by SW1FT** [comment]
`{
  "GEN_BTTR_NTF": true,
  "GEN_SUB_LIST": true,
  "GEN_INF_SCRL": true,
  "GEN_BLUE_GLOW": true,
  "GEN_SDBR_ON": true,
  "VID_END_SHRE": true,
  "VID_DFLT_QLTY": "hd1080",
  "VID_PLST_SEP": true,
  "VID_PLST_ATPL": true,
  "VID_PLST_RVRS": true,
  "VID_PLR_ALVIS": true,
  "VID_PLR_SIZE_MEM": true,
  "VID_PLR_FIT_WDTH": "1280px",
  "VID_HIDE_COMS": "1",
  "VID_POST_TIME": true,
  "VID_VID_CNT": true,
  "VID_DESC_SHRT": true,
  "VID_SDBR_ALGN": "1",
  "VID_PLR_HTML5": true,
  "BLK_ON": true,
  "volLev": 33,
  "plApl": false,
  "plRev": false,
  "advOpts": false,
  "blacklist": {},
  "extLang": {
    "pt_PT": {
      "YTSETS": "Definições do YouTube+",
      "ADV_OPTS": "Opções avançadas",
      "SUB_PLST": "Reproduzir vídeos recentes",
      "GEN_SDBR_ON": "Activar modo barra lateral",
      "SDBR_OPEN": "Abrir barra lateral",
      "BLCK_ADD": "Adicionar à lista negra",
      "BLCK_EDIT": "Editar",
      "BLCK_SAVE": "Guardar",
      "BLCK_CLSE": "Fechar",
      "CNSL_AP": "Início automático",
      "CNSL_RPT": "Repetir vídeo",
      "CNSL_SVTH": "Abrir imagem de fundo",
      "CNSL_SS": "Capturar imagem",
      "CNSL_SS_CLS": "FECHAR",
      "CNSL_SDBR": "Modo barra lateral",
      "CNSL_FLBR": "Modo navegador inteiro",
      "CNSL_CINM_MD": "Modo cinema",
      "CNSL_FRME": "Quadro a quadro",
      "PLST_AP": "Início automático",
      "PLST_RVRS": "Inverter",
      "SHOW_CMTS": "Mostrar comentários",
      "HIDE_CMTS": "Esconder comentários",
      "GLB_IMPR": "Importar/exportar definições",
      "GLB_LOCL_LANG": "Clique para editar a linguagem do YT+",
      "GLB_LOCL_LANG_CSTM": "Local",
      "GLB_IMPR_SAVE": "Guardar e carregar",
      "GLB_RSET": "Repor",
      "GLB_SVE": "Guardar",
      "GLB_SVE_SETS": "Definições salvas",
      "FTR_DESC": "Descubra o que isto faz",
      "GEN": "Geral",
      "VID": "Vídeo",
      "CHN": "Canais",
      "BLK": "Lista negra",
      "ABT": "Sobre",
      "HLP": "Ajuda",
      "DNT": "Doação",
      "GEN_TTL": "Definições gerais",
      "GEN_GEN": "Geral",
      "GEN_LYT": "Aparência",
      "GEN_LOCL_LANG": "Usar linguagem modificada do YT+",
      "GEN_DSBL_ADS": "Desactivar publicidades fora da página de vídeo",
      "GEN_INF_SCRL": "Activar scroll infinito em feeds",
      "GEN_YT_LOGO_LINK": "Logotipo do Youtube redirecciona para as subscrições",
      "GEN_SUB_LIST": "Activar lista de reprodução de subscrições",
      "GEN_REM_APUN": "Remover reprodução automática do vídeo a seguir",
      "GEN_SPF_OFF": "Desactivar SPF",
      "GEN_HIDE_FTR": "Esconder rodapé",
      "GEN_BLUE_GLOW": "Retirar brilho azul em torno dos botões clicados",
      "GEN_HDE_RECM_SDBR": "Esconder barra lateral de canais recomendados",
      "GEN_HDE_SRCH_SDBR": "Esconder barra lateral nos resultados de pesquisa",
      "GEN_HDE_CHN_SDBR": "Esconder barra lateral dos canais",
      "GEN_CMPT_TTLS": "Títulos compactos nas listas",
      "GEN_DSB_HVRC": "Desactivar hovercards",
      "GEN_BTTR_NTF": "Caixa de notificação azul melhorada",
      "GEN_GRID_SUBS": "Subscrições em formato grelha",
      "GEN_GRID_SRCH": "Resultados de pesquisa em formato grelha",
      "VID_TTL": "Definições de vídeo",
      "VID_PLR": "Definições do reproductor",
      "VID_PLR_LYT": "Aspecto do reproductor",
      "VID_DFLT_QLTY": "Qualidade de vídeo padrão:",
      "VID_DFLT_QLTY_AUTO": "Auto",
      "VID_DFLT_QLTY_TNY": "144p",
      "VID_DFLT_QLTY_SML": "240p",
      "VID_DFLT_QLTY_MDM": "360p",
      "VID_DFLT_QLTY_LRG": "480p",
      "VID_DFLT_QLTY_720": "720p",
      "VID_DFLT_QLTY_1080": "1080p",
      "VID_DFLT_QLTY_1440": "1440p",
      "VID_DFLT_QLTY_2160": "2160p (4k)",
      "VID_DFLT_QLTY_2880": "2880p (5k)",
      "VID_DFLT_QLTY_ORIG": "4320p (8k)",
      "VID_PLR_ALVIS": "Reproductor sempre visível ao ler os comentários",
      "VID_PLR_ALVIS_MOVE": "Mover",
      "VID_PLR_ALVIS_RST": "Repôr posição",
      "VID_PLR_ALVIS_SCRL_TOP": "Ir para o topo",
      "VID_PLR_ATPL": "Iniciar vídeos automáticamente",
      "VID_LAYT": "Aparência",
      "VID_VID_CNT": "Mostrar link com número de vídeos carregados",
      "VID_POST_TIME": "Mostrar há quanto tempo o vídeo foi publicado",
      "VID_HIDE_DETLS": "Esconder detalhes do vídeo",
      "VID_HIDE_COMS": "Secção de comentários",
      "VID_HIDE_COMS_SHOW": "Mostrar",
      "VID_HIDE_COMS_HIDE": "Esconder",
      "VID_HIDE_COMS_REM": "Remover",
      "VID_END_SHRE": "Desactivar painel de partilha quando o video acaba",
      "VID_PLST": "Listas",
      "VID_PLST_ATPL": "Activar controlo de início automático das listas",
      "VID_PLST_RVRS": "Activar controlo de inversão das listas",
      "VID_PLR_SIZE_MEM": "Memorizar tamanho do reproductor",
      "VID_VOL_WHEEL": "Alterar nível de som com a roda do rato",
      "VID_PLR_VOL_MEM": "Memorizar volume de audio",
      "VID_PLR_ADS": "Desactivar publicidades na página de vídeo",
      "VID_PLR_ALACT": "Atalhos do reproductor sempre activos",
      "VID_SUB_ADS": "Activar publicidades só para vídeos de canais subscritos",
      "VID_PLR_ANTS": "Desactivar notas",
      "VID_PLR_DASH": "Desactivar reprodução DASH",
      "VID_PLR_HFR": "Desactivar HFR (60fps)",
      "VID_PLR_HTML5": "Usar o reproductor HTML5 quando possível",
      "VID_PLR_CC": "Desactivar legendas e CC",
      "VID_PLR_INFO": "Activar barra de informação com o botão ver mais tarde",
      "VID_PLR_FIT": "Ajustar na página no modo cinema",
      "VID_PLR_FIT_WDTH": "Largura máxima do ajuste na página:",
      "VID_PLR_DYN_SIZE": "Desactivar tamanho dinâmico do reproductor na vista predefinida",
      "VID_DESC_SHRT": "Botões curtos na descrição do vídeo",
      "VID_TTL_CMPT": "Título compacto na descrição do vídeo",
      "VID_SDBR_ALGN": "Alinhar modo barra lateral",
      "VID_SDBR_ALGN_NONE": "Nenhum",
      "VID_SDBR_ALGN_LEFT": "Esquerda",
      "VID_SDBR_ALGN_RIGHT": "Direita",
      "VID_LAYT_AUTO_PNL": "Automáticamente mostrar mais na descrição do vídeo",
      "GEN_CHN_DFLT_PAGE": "Página de canal predefinida:",
      "GEN_CHN_DFLT_PAGE_DFLT": "Padrão",
      "GEN_CHN_DFLT_PAGE_VID": "Vídeos",
      "GEN_CHN_DFLT_PAGE_PL": "Listas de reprodução",
      "GEN_CHN_DFLT_PAGE_CHN": "Canais",
      "GEN_CHN_DFLT_PAGE_DISC": "Discussão",
      "GEN_CHN_DFLT_PAGE_ABT": "Acerca de",
      "BLK_TTL": "Definições da lista negra",
      "BLK_BLK": "Lista negra",
      "BLK_ON": "Activar lista negra",
      "ABT_TTL": "Informação e ligações úteis",
      "ABT_THKS": "Agradecimentos a:",
      "ABT_THKS_YEPPHA": ", cujo trabalho inspirou a criação deste projecto, sem ele nada disto existiria hoje.",
      "ABT_THKS_USERSCRIPT": " por tornarem o processo de produção e publicação de software bastante fácil.",
      "ABT_THKS_STACKOV": " por toda a informação valiosa que contém e que contribui bastante para a criação de software.",
      "ABT_INFO": "Páginas oficiais",
      "ABT_LNK_GHB": "GitHub",
      "ABT_LNK_GRFK": "Greasy Fork",
      "ABT_LNK_OPNU": "OpenUserJS",
      "WLCM": "Obrigado por installar o YouTube+",
      "WLCMSTRT": "Pode modificar as suas definições através do botão acima",
      "LOCALE": "Português",
      "lastMod": 1452028448000
    },
    "nextCheck": 1452991248691
  },
  "firstTime": false,
  "GEN_HDE_CHN_SDBR": false,
  "GEN_HDE_SRCH_SDBR": false,
  "GEN_HDE_RECM_SDBR": false,
  "GEN_HIDE_FTR": false,
  "GEN_CMPT_TTLS": false,
  "GEN_DSB_HVRC": false,
  "GEN_GRID_SRCH": false,
  "GEN_GRID_SUBS": false,
  "GEN_CHN_DFLT_PAGE": "default",
  "GEN_SPF_OFF": false,
  "GEN_REM_APUN": true,
  "GEN_YT_LOGO_LINK": true,
  "GEN_DSBL_ADS": true,
  "GEN_LOCL_LANG": false,
  "VID_LAYT_AUTO_PNL": false,
  "VID_HIDE_DETLS": false,
  "VID_TTL_CMPT": false,
  "VID_PLR_FIT": false,
  "VID_PLR_DYN_SIZE": false,
  "VID_PLR_INFO": true,
  "VID_PLR_HFR": false,
  "VID_PLR_DASH": false,
  "VID_VOL_WHEEL": false,
  "VID_PLR_ALACT": false,
  "VID_PLR_VOL_MEM": true,
  "VID_PLR_ANTS": false,
  "VID_PLR_CC": false,
  "VID_PLR_ATPL": false,
  "VID_SUB_ADS": false,
  "VID_PLR_ADS": true,
  "theaterMode": true,
  "loopVid": false
}`

**Comment by ParticleCore** [comment]
If you are using the userscript version I have pushed a CSS update that should correct this conflict. I was not aware of it because I don't have the black background removed, but from what I can remember it was a previous fix that no longer appears to have any need to exist anymore.

Pressing Ctrl + F5 should update the latest CSS file, otherwise you will have to wait until I release a new add-on version with the updated CSS included.

**Comment by SW1FT** [comment]
I'm using the add-on version, but thank you for fixing this!

**Comment by ParticleCore** [comment]
@SW1FT Sorry for the delay on this, I have been waiting for more changes to justify the upload of a new version but none took place. I have decided to push the new version with just the style update which should prevent your issue in version 1.0.4, let me know if it works.

**Comment by SW1FT** [comment]
@ParticleCore Yes, it works, thank you!

**Comment by SW1FT** [comment]
@ParticleCore This issue came back a few versions ago, but just now I was bothered to write here... Can you do something about this? Thanks!

**Comment by ParticleCore** [comment]
@SW1FT I don't see anything wrong in that screenshot. Could you be more specific?

**Comment by SW1FT** [comment]
@ParticleCore The black background is not supposed to be there since I'm using a stylish script with:
`   .player-api {
     background: transparent;
     background-color: transparent;
   }
   .watch-stage-mode #theater-background {
     display: none;
     background-color: transparent;
   }`

**Comment by ParticleCore** [comment]
The background is being removed for me with those rules and YT+ enabled:

![ss](https://cloud.githubusercontent.com/assets/9222661/18222314/3d99cd42-7183-11e6-9b67-a74d65b6b4bd.png)

Either your stylish script is not configured correctly or you need to reinforce the rules as such:

````css
.player-api { background: transparent !important; background-color: transparent  !important; }
.watch-stage-mode #theater-background { display: none  !important; background-color: transparent  !important; }
````

**Comment by SW1FT** [comment]
@ParticleCore You're right, I had 2 namespace urls from other script that I re-utilized and completely forgot about it. Sorry for bothering you!

**Comment by ParticleCore** [comment]
No problem, it could have been a YouTube update that I was not aware of.
