### ISSUE TITLE
Grid Layout in Subscription Broken as of 5/3/2016

### ISSUE THREAD

**Issue by Delta2401** [ParticleCore/Particle#266]
Browser Name: Mozilla Firefox

Browser Version: 46.0.1

Operating System: Windows 10 Pro x64

Software Type: Not sure what you mean, what software?

Software Version: Not sure what you mean, what software?

Userscript Manager: Greasemonkey

Userscript Version: 2016.04.03

Problem Description: Subscription page on GRID reloads indefinitely, and only half of it manages to load each time (see attachment pictures). It worked fine for months going into today, when it stopped working sometime this evening.

Steps to reproduce: Turn on "Grid Layout in Subscriptions", and visit the Subscription page.

Additional details: Included some helpful pictures:

Setting in question, and possible side effect of the bug (URL).
![options](https://cloud.githubusercontent.com/assets/19678486/15696668/c843825a-2780-11e6-8413-42c88b68c132.jpg)

Here is a screenshot of what is happening when the setting is turned back on. It will essentially keep doing this indefinitely.
![yt off](https://cloud.githubusercontent.com/assets/19678486/15696690/057bb764-2781-11e6-8e3b-8910a1f67f6f.jpg)

**Comment by raymondburrows** [comment]
I just had this problem, this is what I just typed up:


Browser Name: Firefox 
Browser Version: 46.0.1
Operating System: Windows 8.1
Software Type: Add-on
Software Version: 1.2.6

Problem Description: When I load https://www.youtube.com/feed/subscriptions it keeps reloading the page indefinitely.

Steps to reproduce: Problem disappears after disabling the extension with no other modifications, and reappears after reenabling. Reproduced in Chrome, which I have no other extensions on and made no customizations to this extension except to troubleshoot, by enabling General Settings -> Grid layout in subscriptions. Problem was resolved in Firefox by disabling this feature.

Additional details: This problem only appeared today. I had not changed or updated anything since this morning, when it was fine, and my first step to try to solve the problem was to update this extension, which didn't work. I do not have auto-updates of any kind enabled, so it's likely a problem introduced by youtube itself. **Disabling the grid layout feature does not seem to have changed my subscriptions view, perhaps it's time to simply remove it.**

**Comment by Delta2401** [comment]
Side note, also after using it for awhile after this bug - I can say I get sporadic times where YouTube+ also doesn't seem to be working at all, and doesn't show up. When I refresh the page though, for some reason it returns to normal. I wonder if YouTube changed something in the last day or so from their side.

**Comment by HitomiTenshi** [comment]
Just had the same issue, reloading indefinitely and it also has some spacing issues on the subscription page. Everything slides to the left and jumps back in a loop.

**Comment by ParticleCore** [comment]
It seems that YouTube is no longer offering the list layout which YT+ grid depends on to show all videos in grid layout instead of YouTube's limited  "Today", "Yesterday".

For the moment the feature will be scrubbed until something else changes, it is possible this is a temporary problem on YouTube side.

**Comment by ParticleCore** [comment]
I have updated to version 1.2.7 with a temporary fix for this, simply put the feature has been scrubbed for the moment while the problem is still present on the YouTube side.

For anyone using the AMO add-on version its release will be delayed because it needs to pass full review before users can update it, this is not something I can control it is simply how AMO works.

For those using userscripts version 1.2.7 should already be available, let me know if the problem is solved.
