### ISSUE TITLE
Auto-res bug?

### ISSUE THREAD

**Issue by Eisys** [ParticleCore/Particle#65]
I have the auto-resolution set to 1080p. Sometimes when I watch a video, the video stops after the first few seconds and doesnt play until I scroll down and the small video comes up, or if I go to fullscreen and back.
Sometimes the video starts in a lower quality, usually 480p and then after about 10 seconds changes to 720p or 1080p smoothly. Sometimes it's HD from the start and plays fine.

I am not able to reproduce it consistently so I don't know if it's something with my setup or with YT+ but this didn't happen when I was using YTC. With YTC the video was usually HD from the start and played fine. With YT+, there's quite a bit of variation. Here are my settings if useful: http://pastebin.com/CeDFtXrv
Latest Chrome with latest YT+ script.

**Comment by ParticleCore** [comment]
Regarding the occasional starts with lower qualities see https://github.com/ParticleCore/Particle/issues/44#issuecomment-120792478

I am still trying to find a better and less expensive way of avoiding the low quality start, but so far none have worked. I have also observed this with the other extensions that offer that same functionality, as far as I could see, although it might not looked like it for you at that time.

Regarding the video stopping, I have never faced such issue yet and without steps to reproduce I am unable to discover what might be causing it. I suggest that instead you try to disable all the other extensions (including AdGuard which I think you might be using) except YT+ and see if the video stopping issue persists.

**Comment by ParticleCore** [comment]
If you can, please open your console and enter the following `localStorage["yt-player-quality"]`, what does it return?

**Comment by Eisys** [comment]
Sorry about the duplicate. The 'lower quality at first' doesn't really bug me. If it did that all the time I wouldn't mind.

I just disabled every addon I have except for Tamper and this script within it. Still have this problem. I found a [video](https://www.youtube.com/watch?v=fIxwRSKPpjE) where it happened most of the time and was able to test it.

The problem seems to have something to do with DASH. If I disable DASH, the video loads normal without stopping. So I guess I have a workaround atleast. But there's no 1080p or 60fps without DASH so that sucks. If I have DASH enabled but set the auto-res to 720p, then this bug doesn't occur on the same video.

I tested this on my laptop, same thing, although to a lesser extent it would seem. But still happens. So it can't be just my setup. I'm running Win 10, laptop Win 8 Pro.

**Comment by ParticleCore** [comment]
It sounds like you are having this problem, also on Chrome and Windows 8:

https://www.reddit.com/r/youtube/comments/357416/youtube_keep_going_black_randomly/

Disable YT+, select the 1080p quality in the video you linked and refresh the page, YouTube should automatically start the video in 1080p if you don't have cookies disabled. See if the problem keeps happening with YT+.

I tried over 10 times the video you linked with your exact YT+ settings (latest Chrome + Tampermonkey) and not once did it stopped playing before the end. The only difference is I am using Windows 7, I don't have W8 or W10 to test with.

**Comment by Eisys** [comment]
I 100% am using HTML 5: http://prntscr.com/8c8z6t

Disabled everything, went to the video, chose 1080p, refresh, it's in 1080P from the start and it's fine, works perfect.

I cleaned Chrome's browsing data, and ran CCleaner just now. Enabled Tamper again and... it doesn't happen anymore. Tested on the same video and others, no problem. I guess I had old cookies/cache or something that caused this. Although this wouldn't explain why it also happened on my laptop.

So for the time being, I guess it's 'fixed'. I can't know for sure since it comes and goes as it pleases.

Truly sorry to waste your time like this. I should've been smarter and cleaned my shit earlier.

**Comment by ParticleCore** [comment]
Don't be sorry, your feedback is valuable and may help other people that might face the same issue.

If it happens again do let me know and try to see if there are any errors in the console as well, with some luck it might throw some clue about what is causing the problem.

Regarding the low quality starts I have improved it a bit, so far in my tests no videos have started with low quality yet with this method. It will be available when I publish the next update.

**Comment by ParticleCore** [comment]
I have released the new version 0.5.9 with the included improved quality method, let me know if it behaves more consistently.

**Comment by Eisys** [comment]
Update time.
[This is a comment I was going to to post after your last comment here.](https://docs.google.com/document/d/1o5hunDS3SrqtKgRmRCGMhHICdZ4elO3Gxyr_46P2__U/edit?usp=sharing)

But I thought I'd wait a while to make sure. And since that comment, it hasn't happened until today.
I turned everything off one by one, still happened, until I turned off YT+, then it stopped.
I then installed YTC again and loaded my old settings to see if it happens with that as well. It sometimes did, sometimes didn't, but when it did, it only buffered for ~a second and then kept playing.
Then turned off YTC, and turned on YT+ and the original bug happened again.

I also tried turning off SPF. The bug stopped, but when I turned SPF back on again, it didn't come back, until a while later when I tried the same video again just to see if it's back and it was. [The video that this happens in](https://www.youtube.com/watch?v=Cud9Pg9hmB0) is different than the one in the OP(That video plays just fine every single time now). So for now I'll just disable SPF since there isn't a huge difference in speed and see if it happens again.

About the 'low res at first'; that hasn't happened at all since the 0.5.9 update, so thank you for that.
_____________________________________________________________

I'd also like to make a feature request but I'll ask here first if it's something you'd be willing to add.

For a long time I've used [this script](https://gist.github.com/Yonezpt/cf655fe7f9751877fb3d) to hide the header on YT and it's worked well. Recently I edited some of the numbers in the script so the header is completely disabled on video pages and I prefer that. I don't use the header at all when on a video. My [video player size is as big as it can be](http://prntscr.com/8f4yg7) so the header just gets in the way. And to get back to the YT subs page, I just have a bookmark to it above where the YouTube button would be.
So the request is to have an option to completely disable the header when on a video page.

Also, I'd like to see [this script's](https://userstyles.org/styles/118289/youtube-subscribe-counter) functionality added but this is more for convience and is not that important.

Ok so that is it. Sorry for the long comment.

**Comment by ParticleCore** [comment]
The fact that you noticed it happening before even with all extensions disabled suggests that this is not a problem being caused by them but either by the browser itself or YouTube, despite looking like the extensions are causing it.

To see if this is a problem being caused by YouTube use Firefox with a clean profile and just with YT+, if the problem does not appear again then it is most likely not being caused by YouTube itself, try the step below.

To see if this is a problem being caused by the browser reset Chrome to its defaults, don't load any personal preferences from any persona you might be using.

I have been actively using the same setup as yours (Chrome and YT+ with userscript) and I have never faced the video stopping issue once so I am unable to debug the problem on my side.

Regarding your hide header request, it is not something I wish to add for now. But for the purpose that you described you should use the [fullbrowser mode](https://github.com/ParticleCore/Particle/wiki/Features#adv_fullbrowser) instead, it does exactly what you want.

Regarding the other request, it is a YouTube bug. I have previously reported to the YouTube team that the subscriber count was not showing up on the video page, which YouTube already fixed, I have now reported the same issue present in the channel pages. The subscriber count is there, it's just their style files are incorrectly setup so it hides the count when it shouldn't. In the next month or less there should be no need to use a userstyle to read the subscriber count in the channel pages.

**Comment by Eisys** [comment]
Installed Firefox(thanks for reminding me how much I hate it xD), installed Grease and YT+ and it was kind of acting up. But not in the same way. The video was a bit laggy or would lock up for ~a quarter of a sec in the first 3 or 4 seconds and then played fine after that. I don't know if this was just a fault of the browser or something with the video itself. I did try the video before installing anything and it played better than that but was still laggy sometimes in the first few seconds.

After that I uninstalled Chrome and did a fresh install. Video plays fine. Installed Tamper and YT+ and it's played fine since w/o locking up but still has a little video lag in the first few seconds, audio is fine(this might just be because it's a 60fps video).

>Regarding your hide header request, it is not something I wish to add for now. But for the purpose >that you described you should use the fullbrowser mode instead, it does exactly what you want.

Ok, totally fine. The script I'm using still works nicely. It'd be nice to have less separate scripts though. 
I'll just hope that you'll look into adding this option down the line.
And the fullbrowser mode isn't for me. The header still shows and I can't scroll through the page to look at comments/video info/other videos.

Thanks for letting me know that the sub count is there again on video page. I can delete the script now.

**Comment by ParticleCore** [comment]
>And the fullbrowser mode isn't for me. The header still shows and I can't scroll through the page to look at comments/video info/other videos.

The header shouldn't show, it was set to cover the entire page above all elements. It is possible that this is being caused by another userscript/extension. But yes, it does not let you scroll down the page, but if that is the case I'd suggest using this instead: https://greasyfork.org/en/scripts/811-resize-yt-to-window-size

The author made it work with YT+, as long as you disable the YT+ option to make the player always visible when scrolling to comments, just like the author advised.

**Comment by Eisys** [comment]
Yep, turns out that the dark theme script I'm using caused the issue. Disabled it, tried the fullbrowser again and now it's working properly.

But as I said, I don't need any new solution. My edited version of the original script works perfectly, hiding the header. It would be nice not having to use an edited script that's originally meant for something else though.

If I use the 'inspect element' feature on the header and delete this:
#yt-masthead-container
and this:
<div id="masthead-positioner-height-offset"></div>
it does exactly what I want but I just can't put this info into a working userscript myself.
Hence why I just wish it was in your all-in-one script.
