### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by SW1FT** [ParticleCore/Particle#69]
Addon is enabled but the functionality is not, the YT+ panel icon isn't even displayed... 

Also, 0.5.9 is not available in AMO.

**Comment by ParticleCore** [comment]
I don't understand, are you using the add-on version 0.5.8 and it is not working? Open the console and tell me if there is any error showing up. Press Ctrl + Shift + K to open the console.

Also telling me which browser and version you are using might help.

The 0.5.9 add-on delay is due to the review queues, there is nothing I can do about it. The version is there, but only available via the archive section until it is approved: https://addons.mozilla.org/en-US/firefox/addon/youtube-plus/versions/

I just tried both versions with Firefox 40.0.3 and both 0.5.8 and 0.5.9 add-on versions work correctly.

**Comment by ParticleCore** [comment]
I have just published version 0.6.0 with a previous method of DOM creation which I suspect might be the roof of this problem, can you try it out and let me know if it is working correctly again?

You will have to install it from the archive section I previously linked since it is awaiting review.

**Comment by SW1FT** [comment]
Sorry for the lack of info, I'm using Firefox 42.0a2 (Dev Edition). 0.5.8 doesn't work and 0.6.0 doesn't either. I've been using your addon since forever and with the same addons, I've tried disabling all of them but the issue still remains. Regarding the console output, it does not state anything relevant to YT+.

**Comment by ParticleCore** [comment]
Just downloaded the Dev version and installed the three recent YT+ versions, all worked correctly so it appears that something went wrong on your side.

The console output does not distinguish YT+ from a random page script so what you might think is not related to YT+ might actually be.

Before resetting the YT+ settings try clearing your cache and cookies. If the problem still persists then open the console and enter the following `window.postMessage({set: {}}, "*");` , then refresh the page. This resets the YT+ settings to their defaults in case some setting got corrupted.

**Comment by SW1FT** [comment]
Console output: "A codificação de caracteres do documento de texto não foi declarada. O documento será mostrado com texto ilegível em algumas configurações de navegadores se o documento contiver caracteres não pertencentes ao intervalo US-ASCII. A codificação de caracteres necessita de ser declarada no protocolo de transferência ou o ficheiro necessita de utilizar uma marca de ordem de bytes como assinatura da codificação." (view-source:https://s.ytimg.com/yts/jsbin/html5player-new-en_US-vflCeB3p5/html5player-new.js)

Resetting the settings using that command fixed the problem, so I guess something got corrupted...

**Comment by ParticleCore** [comment]
Yes, that one was restricted to the html5 source code so nothing related to YT+ as you suspected. Glad to hear that it is working, too bad we couldn't understand what was it so that I could patch it.

By the way, the new version loads language translations automatically, if you are using YouTube in Português YT+ should show in the same language as well. Is it working for you?

**Comment by SW1FT** [comment]
Yes, the translation is working and it's on point. Thanks for your help.

**Comment by ParticleCore** [comment]
@SW1FT Sorry for pinging you about this after 10 days, but do you remember if you were using the blacklist feature before this issue occured? If so, did you have a long list of channels in your blacklist?
